
@bearerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJmNDc1ODkzNy0xMmQ3LTQ2OWYtYTRkYS1iYTgyMjAwZWVhYjgiLCJpYXQiOjE2ODc0ODQ1OTksImV4cCI6MTY4NzQ4NTE5OX0.A4SshDnYBjcsCaQtlqU7OUJejzrlnX_7BbxF1EyH6zQ

### Create City
POST http://localhost:3333/cities
content-type: application/json
Authorization: {{bearerToken}}

{
    "name": "São Paulo",
    "state": "SP"
}
