
### CREATE ADMIN
POST http://localhost:3333/users
content-type: application/json

{
    "name": "São Paulo",
    "email": "admin@gmail.com",
    "password": "admin123",
    "role": "ADMIN"
}


### GET MEALS HISTORY BY USER
POST http://localhost:3333/users
content-type: application/json

{
    "name": "São Paulo",
    "email": "org@gmail.com",
    "password": "org123",
    "role": "ORG",
    "cellphoneNumber": "123",
    "address":{
        "cityName": "São Paulo",
        "street": "Rua test",
        "zipCode": "0123123"
    }
}

### AUTHENTICATE
POST http://localhost:3333/login
content-type: application/json

{
    "email": "org@gmail.com",
    "password": "org123"
}


### AUTHENTICATE
POST http://localhost:3333/login
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin123"
}
