
@bearerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiT1JHIiwic3ViIjoiZGIxMjI0ZDgtYWE0MC00NTljLTk0ZjMtYzcwYjEwYmEwMzUzIiwiaWF0IjoxNjg3NDg0NjcwLCJleHAiOjE2ODc1NzEwNzB9._pzeSt_jtD6c2AZPBC22gzGopoyW5ubwhRtwMXuWLiw

### Create Pet
POST http://localhost:3333/pets
content-type: application/json
Authorization: {{bearerToken}}

{
    "name": "Pepeto",
    "age": 2,
    "about": "Misturado com york e pincher",
    "size": "SMALL",
    "energyLevel": "HIGH",
    "independencyLevel": "MEDIUM",
    "environment": "Normal",
    "requirements": [
        "Necessário dar banho regularmente"
    ]
}


### Search Pets
POST http://localhost:3333/pets/search
content-type: application/json

{
   "city": "São"
}

### Search by petid
GET http://localhost:3333/pets/070be8ff-5747-4f9b-884e-ac9b12cf8862
content-type: application/json


